validação das questões
Fatec-Bug-Busters/scrum-academy pull request #5
Opened 2024-05-12 19:30 UTC by DaviMBDev

Validação das questões com JS feita, tanto nos quizzes que estão disponíveis até o momento quanto no exame final. 
Podem ser feitas melhorias visuais ainda no pop-up

2024-05-12 19:50 UTC, DigoCast reviewed
adicionando review

2024-05-12 19:50 UTC, DigoCast reviewed
Review

2024-05-12 19:52 UTC, DigoCast approved these changes
Review

2024-05-13 00:01 UTC, WesleyGoncalves requested changes

2024-05-13 00:01 UTC, WesleyGoncalves commented on src/templates/conteudos/artefatos-e-eventos-1.html
> +
Os blocos scripts poderiam ser colocados no final da página para não atrapalhar a renderização da pag feita pelo navegador.

A gente pode criar um block na pag base logo antes do fechamento do body (`</body>`) para que os scripts sejam inseridos nesse block. 

E na página que implementar os scripts, chamaria esse block +- assim:

```html 
{% block scripts %}
<script type="text/javascript">
...
</scripts>
{% endblock scripts %}
```

O que acham?

2024-05-16 21:16 UTC, WesleyGoncalves approved these changes

2024-05-16 21:16 UTC, WesleyGoncalves commented on src/templates/conteudos/artefatos-e-eventos-1.html
> +{%block quizjs}
@DaviMBDev faltou um % no fechamento dos blocks, por isso, está dando erro nos botões Próximo. 

`{%block quizjs}` => `{% block quizjs %}`

2024-05-20 20:21 UTC, merged